// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tradeborn.Infrastructure.Persistence;

#nullable disable

namespace Tradeborn.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradebornDbContext))]
    [Migration("20260728145140_QuestsAndCounters")]
    partial class QuestsAndCounters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.AuditLedgerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BalanceAfterCent")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("MoneyDeltaCent")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceDeltas")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("PlayerId", "OccurredAtUtc");

                    b.ToTable("audit_ledger", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.BuildingCostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId", "ResourceId")
                        .IsUnique();

                    b.ToTable("building_costs", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.BuildingDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("BuildCostCoins")
                        .HasColumnType("bigint");

                    b.Property<long>("BuildSeconds")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCityCentre")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrePlaced")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipeId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("StoragePerResource")
                        .HasColumnType("bigint");

                    b.Property<int>("UnlockCityLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("building_definitions", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.CityBuildingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Col")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HaltReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("OutputBuffer")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PendingLevel")
                        .HasColumnType("integer");

                    b.Property<long>("ProgressMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "Col", "Row")
                        .IsUnique();

                    b.ToTable("city_buildings", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BalanceCent")
                        .HasColumnType("bigint");

                    b.Property<long>("DeliveriesCompleted")
                        .HasColumnType("bigint");

                    b.Property<int>("GridSize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSettledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<long>("SalesCompleted")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.CityInventoryEntity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("CityId", "ResourceId");

                    b.ToTable("city_inventory", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.CityPlotEntity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Col")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("Terrain")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Unlocked")
                        .HasColumnType("boolean");

                    b.HasKey("CityId", "Col", "Row");

                    b.ToTable("city_plots", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.IdempotencyKeyEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "Key");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.MarketPriceEntity", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastTradeAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PriceAtLastTradeCent")
                        .HasColumnType("bigint");

                    b.HasKey("ResourceId");

                    b.ToTable("market_prices", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.MarketPriceHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PriceCent")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "RecordedAtUtc");

                    b.ToTable("market_price_history", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.PlayerQuestEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId", "QuestId");

                    b.ToTable("player_quests", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.RecipeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("CycleMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("TopologicalRank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.RecipeIngredientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOutput")
                        .HasColumnType("boolean");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "ResourceId", "IsOutput")
                        .IsUnique();

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.ResourceDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("BasePriceCoins")
                        .HasColumnType("bigint");

                    b.Property<long>("MarketDepth")
                        .HasColumnType("bigint");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("resource_definitions", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.TransportJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ArrivesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DepartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromBuildingId")
                        .HasColumnType("uuid");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("FromBuildingId");

                    b.HasIndex("CityId", "ArrivesAtUtc");

                    b.ToTable("transport_jobs", (string)null);
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.BuildingCostEntity", b =>
                {
                    b.HasOne("Tradeborn.Infrastructure.Persistence.BuildingDefinitionEntity", null)
                        .WithMany("Costs")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.CityBuildingEntity", b =>
                {
                    b.HasOne("Tradeborn.Infrastructure.Persistence.CityEntity", null)
                        .WithMany("Buildings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.CityEntity", b =>
                {
                    b.HasOne("Tradeborn.Infrastructure.Persistence.PlayerEntity", "Player")
                        .WithOne("City")
                        .HasForeignKey("Tradeborn.Infrastructure.Persistence.CityEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.CityInventoryEntity", b =>
                {
                    b.HasOne("Tradeborn.Infrastructure.Persistence.CityEntity", null)
                        .WithMany("Inventory")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.CityPlotEntity", b =>
                {
                    b.HasOne("Tradeborn.Infrastructure.Persistence.CityEntity", null)
                        .WithMany("Plots")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.RecipeIngredientEntity", b =>
                {
                    b.HasOne("Tradeborn.Infrastructure.Persistence.RecipeEntity", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.TransportJobEntity", b =>
                {
                    b.HasOne("Tradeborn.Infrastructure.Persistence.CityEntity", null)
                        .WithMany("Transports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.BuildingDefinitionEntity", b =>
                {
                    b.Navigation("Costs");
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.CityEntity", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Inventory");

                    b.Navigation("Plots");

                    b.Navigation("Transports");
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.PlayerEntity", b =>
                {
                    b.Navigation("City");
                });

            modelBuilder.Entity("Tradeborn.Infrastructure.Persistence.RecipeEntity", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
